spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    template:
      default-topic: book-lib-event
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092, localhost:9093, localhost:9094

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bookLibDB
    driver-class-name: org.h2.Driver

#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  kafka:
#    producer:
#      bootstrap-servers: prod:9092
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
